"""產出 docs/tw-industry.js:台股個股→官方產業別對照 + 主題分類(看盤頁分類頁籤用)。
資料源 TWSE openapi t187ap03_L(上市)+ TPEx openapi(上櫃),免 token;產業別代碼→名稱
用官方代碼表。ETF 用 stocks.js 裡 00 開頭代碼歸類。跑一次產靜態檔,需要更新重跑再部署 docs。
主題分類=公認概念股靜態清單(事實分組,非投資建議)。"""
import json
import os
import re
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
DOCS = os.path.join(os.path.dirname(HERE), "docs")
OUT = os.path.join(DOCS, "tw-industry.js")
TWSE = "https://openapi.twse.com.tw/v1/opendata/t187ap03_L"
TPEX = "https://www.tpex.org.tw/openapi/v1/mopsfin_t187ap03_O"

IND_CODE = {
    "01": "水泥工業", "02": "食品工業", "03": "塑膠工業", "04": "紡織纖維", "05": "電機機械",
    "06": "電器電纜", "08": "玻璃陶瓷", "09": "造紙工業", "10": "鋼鐵工業", "11": "橡膠工業",
    "12": "汽車工業", "14": "建材營造", "15": "航運業", "16": "觀光餐旅", "17": "金融保險",
    "18": "貿易百貨", "19": "綜合", "20": "其他", "21": "化學工業", "22": "生技醫療",
    "23": "油電燃氣", "24": "半導體業", "25": "電腦及週邊", "26": "光電業", "27": "通信網路",
    "28": "電子零組件", "29": "電子通路", "30": "資訊服務", "31": "其他電子", "32": "文化創意",
    "33": "農業科技", "34": "電子商務", "35": "綠能環保", "36": "數位雲端", "37": "運動休閒", "38": "居家生活",
}

THEMES = {
    "AI 概念": ["2330", "2454", "3661", "3231", "2382", "2376", "6669", "3443", "2308", "3017",
                "3037", "2345", "4966", "3529", "8299", "3008", "6415", "2379", "3034", "5274"],
    "半導體供應鏈": ["2330", "2303", "2454", "3711", "2379", "3034", "3443", "5347", "6488", "3105",
                     "2408", "2344", "6770", "3532", "5483", "6182", "3661", "3529", "4966", "8016"],
    "高股息 ETF 熱門": ["0056", "00878", "00919", "00929", "00940", "0050", "006208"],
}


def _fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0", "Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read().decode())


def _etf_codes():
    """從 docs/stocks.js 的 TW_STOCKS_FULL 抽 00 開頭代碼當 ETF 群。"""
    src = open(os.path.join(DOCS, "stocks.js"), encoding="utf-8").read()
    m = re.search(r"const TW_STOCKS_FULL = \[(.*?)\];", src, re.S)
    if not m:
        return []
    return sorted(set(re.findall(r'\["(00\d{2,4}[A-Z]?)"', m.group(1))))


def main():
    ind = {}
    for url in (TWSE, TPEX):
        for r in _fetch(url):
            sid = str(r.get("公司代號", "")).strip()
            code = str(r.get("產業別", "")).strip().zfill(2)
            if not (sid[:1].isdigit() and 4 <= len(sid) <= 6):
                continue
            cat = IND_CODE.get(code)
            if cat:
                ind[sid] = cat
    for sid in _etf_codes():
        ind.setdefault(sid, "ETF")
    cats = {}
    for sid, cat in ind.items():
        cats.setdefault(cat, []).append(sid)
    cats = {c: sorted(v) for c, v in sorted(cats.items(), key=lambda kv: -len(kv[1]))}
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/build_tw_industry.py — FinMind TaiwanStockInfo\n")
        f.write("const TW_INDUSTRY = " + json.dumps(ind, ensure_ascii=False, separators=(",", ":")) + ";\n")
        f.write("const TW_CATEGORIES = " + json.dumps(cats, ensure_ascii=False, separators=(",", ":")) + ";\n")
        f.write("const TW_THEMES = " + json.dumps(THEMES, ensure_ascii=False, separators=(",", ":")) + ";\n")
    print(f"{len(ind)} 檔 / {len(cats)} 個產業別 → {OUT} ({os.path.getsize(OUT)//1024}KB)")
    top = list(cats.items())[:8]
    print("最大分類:", [(c, len(v)) for c, v in top])


if __name__ == "__main__":
    main()
