"""產出 docs/tw-profile.js:台股公司基本資料(董事長/總經理/上市年/發行股數/網址)。
源 TWSE t187ap03_L(上市)+ TPEx t187ap03_O(上櫃),免 token。發行股數給前端算市值(股數×現價)。
需要更新重跑本腳本再部署 docs(異動極少,季跑即可)。"""
import json
import os
import subprocess
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "docs", "tw-profile.js")
SOURCES = [
    "https://openapi.twse.com.tw/v1/opendata/t187ap03_L",
    "https://www.tpex.org.tw/openapi/v1/mopsfin_t187ap03_O",
]


def _fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0", "Accept": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=40) as r:
            return json.loads(r.read().decode())
    except Exception:
        out = subprocess.run(["curl", "-s", "--max-time", "40", "-H", "User-Agent: Mozilla/5.0",
                              "-H", "Accept: application/json", url], capture_output=True, timeout=50)
        return json.loads(out.stdout.decode())


def _year(v):
    """TWSE openapi 上市日期=西元 YYYYMMDD;TPEx 可能民國 YYYMMDD——依長度/開頭判別。"""
    s = str(v or "").strip()
    if not s.isdigit():
        return None
    if len(s) == 8 and s[:2] in ("19", "20"):
        return s[:4]
    if len(s) in (6, 7):
        return str(int(s[:-4]) + 1911)
    return None


def main():
    prof = {}
    for url in SOURCES:
        try:
            rows = _fetch(url)
        except Exception as ex:
            print(f"{url} 失敗:{ex}")
            continue
        for r in rows:
            sid = str(r.get("公司代號", "")).strip()
            if not (sid[:1].isdigit() and 4 <= len(sid) <= 6):
                continue
            shares = str(r.get("已發行普通股數或TDR原股發行股數", "")).replace(",", "").strip()
            web = (r.get("網址") or "").strip()
            if web and not web.startswith("http"):
                web = "https://" + web
            prof[sid] = [
                (r.get("董事長") or "").strip()[:20],
                (r.get("總經理") or "").strip()[:20],
                _year(r.get("上市日期") or r.get("上櫃日期")),
                int(shares) if shares.isdigit() else None,
                web[:80],
            ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/build_tw_profile.py — TWSE/TPEx openapi\n")
        f.write("// {code: [董事長, 總經理, 上市年, 發行股數, 網址]}\n")
        f.write("const TW_PROFILE = " + json.dumps(prof, ensure_ascii=False, separators=(",", ":")) + ";\n")
    print(f"{len(prof)} 檔 → {OUT} ({os.path.getsize(OUT)//1024}KB)")


if __name__ == "__main__":
    main()
